//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_ResultsForUser
    {
        public int IdResult { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdExam { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> ExamDay { get; set; }
        public string KetQuaThi { get; set; }
        public string Time { get; set; }
        public string IdUser { get; set; }
    
        public virtual ExamForUser ExamForUser { get; set; }
    }
}
