//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamForUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamForUser()
        {
            this.Exam_ResultsForUser = new HashSet<Exam_ResultsForUser>();
            this.Question_ExamForUser = new HashSet<Question_ExamForUser>();
        }
    
        public int IdExam { get; set; }
        public Nullable<System.DateTime> Exam_date { get; set; }
        public int Time { get; set; }
        public int NumberQ { get; set; }
        public string NameExam { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string MordifierBy { get; set; }
        public string idUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_ResultsForUser> Exam_ResultsForUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_ExamForUser> Question_ExamForUser { get; set; }
    }
}
