//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Exam_Results = new HashSet<Exam_Results>();
            this.Question_Exam = new HashSet<Question_Exam>();
        }
    
        public int IdExam { get; set; }
        public Nullable<System.DateTime> Exam_date { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public int Time { get; set; }
        public int NumberQ { get; set; }
        public string NameExam { get; set; }
        public bool isactive { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string MordifierBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Results> Exam_Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Exam> Question_Exam { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
