//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int IdQuestion { get; set; }
        public string Contentt { get; set; }
        public string HinhAnh { get; set; }
        public string optionA { get; set; }
        public string optionB { get; set; }
        public string optionC { get; set; }
        public string optionD { get; set; }
        public Nullable<int> IdExam { get; set; }
        public Nullable<int> IdDifficulty { get; set; }
        public Nullable<int> IdDapan { get; set; }
        public string DapAn { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
