//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCs.Models
{
    using DoAnCs.Models.Viewmodel;
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Question_Exam = new HashSet<Question_Exam>();
        }
    
        public int IdQuestion { get; set; }
        public string Contentt { get; set; }
        public string HinhAnh { get; set; }
        public string answer { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> idtopic { get; set; }
        public Nullable<System.DateTime> MordifierDate { get; set; }
        public string Difficult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Exam> Question_Exam { get; set; }
        public virtual Topic Topic { get; set; }
        public List<SubjectItem> AnswerList { get; set; }

    }
}
